databases:
  - name: wordhex-db

services:
  - type: web
    name: wordhex-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run prisma:generate
    startCommand: bash -c "npm run prisma:migrate && npm run prisma:seed && npm run server"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: wordhex-db
          property: connectionString
    healthCheckPath: /api/leaderboard
